project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - cv.qmd
    - blog.qmd

website:
  title: ""
  favicon: "logo_naf2.png"
  navbar:
    logo: "logo_naf.png"
    background: "#A7D5E8"
    align: center
    collapse-below: lg
    left:
      - text: "About"
        href: about.qmd
      - text: CV
        href: cv2.pdf
        
  page-footer:
    left: "Made with <i class='bi bi-balloon-heart-fill'></i> and [Posit Quarto](https://quarto.org/)"
    border: false

format:
  html:
    theme:
      light: [cosmo, style/dsbox.scss]
      dark: [cosmo, style/dsbox.scss, style/dark.scss]
    toc: true
    mainfont: "Atkinson Hyperlegible"

freeze: auto
editor: visual

